### PR TITLE
partials for reviewing products

### PR DESCRIPTION
**Pull request by af19**
@robotpony

### CODE REVIEW

**Comment by robotpony** [comment]
Nicely done @af19.

Did you test this in FF/IE?

**Comment by af19** [comment]
It's OK in Firefox. Not sure about IE.

**Comment by robotpony** [comment]
You'll have to get a VM installed for light IE testing (11/12 are fine). Microsoft provides free VMs for this, let me know if you can't find them online.

**Comment by af19** [comment]
@robotpony 

tested in ie 11. ✅

**Comment by robotpony** [comment]
Awesome sauce.

**Pull request merged**
